version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather_dw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
    - "80:80"
    depends_on:
    - postgres
    volumes:
    - pgadmin_data:/var/lib/pgadmin
            

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  airflow-webserver:
    image: apache/airflow:2.6.3
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/weather_dw
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://postgres:postgres@postgres:5432/weather_dw
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      PYTHONPATH: /opt/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: >
        pandas
        requests
        sqlalchemy
        psycopg2-binary
        python-dotenv
        pyarrow
    depends_on:
      - postgres
      - redis
    volumes:
      - ../dags:/opt/airflow/dags
      - ../scripts:/opt/airflow/scripts
      - ../data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.6.3
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/weather_dw
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://postgres:postgres@postgres:5432/weather_dw
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      PYTHONPATH: /opt/airflow
    depends_on:
      - postgres
      - redis
      - airflow-webserver
    volumes:
      - ../dags:/opt/airflow/dags
      - ../scripts:/opt/airflow/scripts
      - ../data:/opt/airflow/data
    command: scheduler

  airflow-worker:
    image: apache/airflow:2.6.3
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/weather_dw
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://postgres:postgres@postgres:5432/weather_dw
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      PYTHONPATH: /opt/airflow
    depends_on:
      - postgres
      - redis
      - airflow-webserver
    volumes:
      - ../dags:/opt/airflow/dags
      - ../scripts:/opt/airflow/scripts
      - ../data:/opt/airflow/data
    command: celery worker

volumes:
  postgres_data:
